apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: robot
  labels:
    app: robot
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robot
      version: v1
  template:
    metadata:
      labels:
        app: robot
        version: v1
    spec:
      containers:
        - resources:
            limits:
              cpu: '4'
              memory: 4000Mi
            requests:
              cpu: '2'
              memory: 2000Mi
          terminationMessagePath: /dev/termination-log
          name: robot
          securityContext:
            privileged: false
          ports:
            - name: robot
              containerPort: 30000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: quay.io/andyyuen/robot:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: robot
      serviceAccount: robot
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: robot
  labels:
    app: robot
    service: robot
spec:
  ports:
    - name: robot
      protocol: TCP
      port: 30000
      targetPort: 30000
      nodePort: 30000
  type: NodePort
  sessionAffinity: None
  selector:
    app: robot

